services:
  postgres:
    image: postgres:15
    container_name: notifyhub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: notifyhub
      POSTGRES_USER: notifyhub_user
      POSTGRES_PASSWORD: notifyhub_password
      # Create additional database for SonarQube
      POSTGRES_MULTIPLE_DATABASES: notifyhub,sonarqube
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U notifyhub_user -d notifyhub']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: notifyhub-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5

  sonarqube:
    image: sonarqube:latest
    container_name: notifyhub-sonarqube
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube
      SONAR_JDBC_USERNAME: notifyhub_user
      SONAR_JDBC_PASSWORD: notifyhub_password
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
      SONAR_SEARCH_JAVAADDITIONALOPTS: '-Dnode.store.allow_mmap=false'
    ports:
      - '9000:9000'
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -f http://localhost:9000/api/system/status || exit 1',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

volumes:
  postgres_data:
  redis_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
